### ISSUE TITLE
New version of cuDSS

### ISSUE THREAD

**Issue by mipals** [exanauts/CUDSS.jl#62]
Hi there,

There is now a 0.4.0 release of cuDSS. Any plans of updating the wrapper? If not I will give it a go. 

Cheers,
Mikkel

**Comment by amontoison** [comment]
Hi @mipals, I can do that today.
I was not aware of a new release!

**Comment by mipals** [comment]
Sounds good! I think it was realized here in December so it is also a fairly new release 😄

**Comment by amontoison** [comment]
For information, it was release yesterday (2024-12-10).
They added batch sparse linear solvers in the new release, a feature that we requested :+1: 
A new `CUDSS_jll.jl` is coming: https://github.com/JuliaPackaging/Yggdrasil/pull/9990

**Comment by mipals** [comment]
Thanks for the info. I am mostly interested in the improved reordering as my application seems to spend a lot of time in the initial phase. What is the main application for batching?

**Comment by amontoison** [comment]
@mipals I have opened a PR, you use the related branch if you want to test the new version but an update of CUDSS.jl.

For the batch, you could have systems where the left-hand side depends on a paramater `\alpha` and you want to solve it for various values of `\alpha`.
The idea is to use this batch linear solver in a batch optimization solver where you can solve the same optimization problem with a few variants.
